### ISSUE TITLE
Xbox One issues

### ISSUE THREAD

**Issue by enricostano** [quantus/xbox-one-controller-protocol#2]
Hi there, first thing many thanks for your efforts! :clap:

Not sure if strictly related with your work, but we're having some issue with latest (I guess) model of Xbox One controller.

Maybe you can shade some light here https://bbs.archlinux.org/viewtopic.php?id=208569

Many thanks and keep the awesome work!

**Comment by quantus** [comment]
Hi!

My original plan was just do document the communication protocol enough to make it possible to write unofficial drivers for the device and I somewhat succeeded doing it. Unfortunately I haven't had the motivation or time to keep up with all the changes, like differences between new controllers (or firmware versions). If the latest controller/firmware broke something you might want to contact some of the driver authors instead. I assume that at least SteamOS developers are interested in supporting all the different controllers, so they might already have a fix for the problem you are having.

Good luck!

**Comment by enricostano** [comment]
Many thanks for you response! Yes actually the `steamos-xpad` module supports the new Xbox One model https://aur.archlinux.org/packages/steamos-xpad-dkms/ :tada:
