### ISSUE TITLE
The start messages listed here don't work with the new Xbox One S-era controller

### ISSUE THREAD

**Issue by scratchee** [quantus/xbox-one-controller-protocol#3]
I've found that sending an additional 3 bytes with the start message, making it:

0x05
0x20
0x00
0x01
0x00

seems to work, and lines up with other programs that interact with the xboxone controllers.

Note the 0x01 on the 4th byte. Without that, it continues to fail.

I make no claims as to the meaning of these extra bytes, but I can confirm that they still work with the original xboxone controller.

**Comment by quantus** [comment]
Thank you for letting me know about this new start command! I added it to the README to keep it up to date.
