### ISSUE TITLE
Xbox One S or Previous version?

### ISSUE THREAD

**Issue by ghost** [quantus/xbox-one-controller-protocol#6]
Is this for the Xbox One S protocol?

Thank you

**Comment by quantus** [comment]
This was done for the original xbox one's controller and I don't know if the protocol is still the same with the latest controllers. I'd assume that they keep the same protocol for the part that this project covers, as at least I'm unaware that there would have been any major changes.

**Comment by ghost** [comment]
Is this protocol that you have here just the bluetooth profile called: Xbox Bluetooth Gamepad?

**Comment by quantus** [comment]
This is only for the protocol the original controller uses when it connects to the PC with wired USB connection. I haven't done any work to figure out what the protocol is over the xbox one wireless dongle (old controllers), or the newer controllers that are communicating over the Bluetooth.
